// <auto-generated />
using System;
using DogShelter.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogShelter.Services.Migrations
{
    [DbContext(typeof(DogShelterContext))]
    [Migration("20260723112047_MakePasSlikaNaslovnaRequired")]
    partial class MakePasSlikaNaslovnaRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogShelter.Services.Database.AktivnostVolontera", b =>
                {
                    b.Property<int>("AktivnostVolonteraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AktivnostVolonteraId"));

                    b.Property<decimal>("BrojSati")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("DatumAktivnosti")
                        .HasColumnType("date");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipAktivnostiId")
                        .HasColumnType("int");

                    b.Property<int>("VolonterId")
                        .HasColumnType("int");

                    b.HasKey("AktivnostVolonteraId");

                    b.HasIndex("TipAktivnostiId");

                    b.HasIndex("VolonterId");

                    b.ToTable("AktivnostVolontera", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Dogadjaj", b =>
                {
                    b.Property<int>("DogadjajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DogadjajId"));

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaPutanja")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DogadjajId");

                    b.ToTable("Dogadjaj", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.DogadjajVolonter", b =>
                {
                    b.Property<int>("DogadjajVolonterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DogadjajVolonterId"));

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int>("VolonterId")
                        .HasColumnType("int");

                    b.HasKey("DogadjajVolonterId");

                    b.HasIndex("VolonterId");

                    b.HasIndex(new[] { "DogadjajId", "VolonterId" }, "UQ_DogadjajVolonter")
                        .IsUnique();

                    b.ToTable("DogadjajVolonter", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Donacija", b =>
                {
                    b.Property<int>("DonacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonacijaId"));

                    b.Property<DateTime>("DatumDonacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ObradioKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("RazlogOdbijanja")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RazlogVracanja")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StatusDonacijeId")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipDonacijeId")
                        .HasColumnType("int");

                    b.HasKey("DonacijaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObradioKorisnikId");

                    b.HasIndex("StatusDonacijeId");

                    b.HasIndex("TipDonacijeId");

                    b.ToTable("Donacija", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Grad", b =>
                {
                    b.Property<int>("GradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GradId");

                    b.ToTable("Grad", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Korisnik_Aktivan");

                    b.Property<DateTime>("DatumRegistracije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Korisnik_DatumRegistracije");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SlikaPutanja")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("KorisnikId");

                    b.HasIndex("GradId");

                    b.HasIndex(new[] { "Email" }, "UQ_Korisnik_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "KorisnickoIme" }, "UQ_Korisnik_KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.KorisnikUloga", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaId");

                    b.HasIndex("UlogaId");

                    b.HasIndex(new[] { "KorisnikId", "UlogaId" }, "UQ_KorisnikUloga")
                        .IsUnique();

                    b.ToTable("KorisnikUloga", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.LozinkaResetToken", b =>
                {
                    b.Property<int>("LozinkaResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LozinkaResetTokenId"));

                    b.Property<DateTime>("DatumKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("Iskoristen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IsticeU")
                        .HasColumnType("datetime2");

                    b.Property<string>("KodHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("LozinkaResetTokenId");

                    b.HasIndex(new[] { "KorisnikId" }, "IX_LozinkaResetToken_KorisnikId");

                    b.ToTable("LozinkaResetToken", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Notifikacija", b =>
                {
                    b.Property<int>("NotifikacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotifikacijaId"));

                    b.Property<DateTime>("DatumKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Procitano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VezaniEntitetId")
                        .HasColumnType("int");

                    b.HasKey("NotifikacijaId");

                    b.HasIndex(new[] { "KorisnikId", "Procitano" }, "IX_Notifikacija_Korisnik_Procitano");

                    b.ToTable("Notifikacija", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Obavijest", b =>
                {
                    b.Property<int>("ObavijestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObavijestId"));

                    b.Property<bool>("Aktivna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumObjave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaPutanja")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ObavijestId");

                    b.HasIndex("AutorId");

                    b.ToTable("Obavijest", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Pas", b =>
                {
                    b.Property<int>("PasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasId"));

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Pas_Aktivan");

                    b.Property<DateOnly>("DatumPrijema")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RasaId")
                        .HasColumnType("int");

                    b.Property<string>("SlikaNaslovna")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Spol")
                        .HasColumnType("int");

                    b.Property<int>("StatusPsaId")
                        .HasColumnType("int");

                    b.Property<bool>("Sterilizovan")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Tezina")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("Vakcinisan")
                        .HasColumnType("bit");

                    b.Property<int>("VelicinaPsaId")
                        .HasColumnType("int");

                    b.HasKey("PasId");

                    b.HasIndex("RasaId");

                    b.HasIndex("StatusPsaId");

                    b.HasIndex("VelicinaPsaId");

                    b.ToTable("Pas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Posjeta", b =>
                {
                    b.Property<int>("PosjetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosjetaId"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ObradioKorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("PasId")
                        .HasColumnType("int");

                    b.Property<string>("RazlogOtkazivanja")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StatusPosjeteId")
                        .HasColumnType("int");

                    b.HasKey("PosjetaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObradioKorisnikId");

                    b.HasIndex("PasId");

                    b.HasIndex("StatusPosjeteId");

                    b.ToTable("Posjeta");
                });

            modelBuilder.Entity("DogShelter.Services.Database.PregledPsa", b =>
                {
                    b.Property<int>("PregledPsaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PregledPsaId"));

                    b.Property<DateTime>("DatumPregleda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PasId")
                        .HasColumnType("int");

                    b.HasKey("PregledPsaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PasId");

                    b.ToTable("PregledPsa", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Rasa", b =>
                {
                    b.Property<int>("RasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RasaId"));

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Rasa_Aktivan");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RasaId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_Rasa")
                        .IsUnique();

                    b.ToTable("Rasa", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.RevokedToken", b =>
                {
                    b.Property<int>("RevokedTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RevokedTokenId"));

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RevokedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("RevokedTokenId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex(new[] { "Jti" }, "UQ_RevokedToken_Jti")
                        .IsUnique();

                    b.ToTable("RevokedToken", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.SlikaPsa", b =>
                {
                    b.Property<int>("SlikaPsaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlikaPsaId"));

                    b.Property<int>("PasId")
                        .HasColumnType("int");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("int");

                    b.HasKey("SlikaPsaId");

                    b.HasIndex("PasId");

                    b.ToTable("SlikaPsa", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusDonacije", b =>
                {
                    b.Property<int>("StatusDonacijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusDonacijeId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusDonacijeId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_StatusDonacije")
                        .IsUnique();

                    b.ToTable("StatusDonacije", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusPosjete", b =>
                {
                    b.Property<int>("StatusPosjeteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusPosjeteId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusPosjeteId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_StatusPosjete")
                        .IsUnique();

                    b.ToTable("StatusPosjete", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusPsa", b =>
                {
                    b.Property<int>("StatusPsaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusPsaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusPsaId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_StatusPsa")
                        .IsUnique();

                    b.ToTable("StatusPsa", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusZahtjeva", b =>
                {
                    b.Property<int>("StatusZahtjevaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusZahtjevaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusZahtjevaId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_StatusZahtjeva")
                        .IsUnique();

                    b.ToTable("StatusZahtjeva", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.TipAktivnosti", b =>
                {
                    b.Property<int>("TipAktivnostiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipAktivnostiId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipAktivnostiId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_TipAktivnosti")
                        .IsUnique();

                    b.ToTable("TipAktivnosti", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.TipDonacije", b =>
                {
                    b.Property<int>("TipDonacijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipDonacijeId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipDonacijeId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_TipDonacije")
                        .IsUnique();

                    b.ToTable("TipDonacije", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Udomljavanje", b =>
                {
                    b.Property<int>("UdomljavanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UdomljavanjeId"));

                    b.Property<DateOnly>("DatumUdomljavanja")
                        .HasColumnType("date");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ZahtjevZaUdomljavanjeId")
                        .HasColumnType("int");

                    b.HasKey("UdomljavanjeId");

                    b.HasIndex(new[] { "ZahtjevZaUdomljavanjeId" }, "UQ_Udomljavanje")
                        .IsUnique();

                    b.ToTable("Udomljavanje", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UlogaId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_Uloga_Naziv")
                        .IsUnique();

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.VelicinaPsa", b =>
                {
                    b.Property<int>("VelicinaPsaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VelicinaPsaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VelicinaPsaId");

                    b.HasIndex(new[] { "Naziv" }, "UQ_VelicinaPsa")
                        .IsUnique();

                    b.ToTable("VelicinaPsa", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.Volonter", b =>
                {
                    b.Property<int>("VolonterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolonterId"));

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("DatumPridruzivanja")
                        .HasColumnType("date");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("VolonterId");

                    b.HasIndex(new[] { "KorisnikId" }, "UQ_Volonter")
                        .IsUnique();

                    b.ToTable("Volonter", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.ZahtjevZaUdomljavanje", b =>
                {
                    b.Property<int>("ZahtjevZaUdomljavanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZahtjevZaUdomljavanjeId"));

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPodnosenja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ObradioKorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PasId")
                        .HasColumnType("int");

                    b.Property<string>("RazlogOdbijanja")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StatusZahtjevaId")
                        .HasColumnType("int");

                    b.HasKey("ZahtjevZaUdomljavanjeId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObradioKorisnikId");

                    b.HasIndex("PasId");

                    b.HasIndex("StatusZahtjevaId");

                    b.ToTable("ZahtjevZaUdomljavanje", (string)null);
                });

            modelBuilder.Entity("DogShelter.Services.Database.AktivnostVolontera", b =>
                {
                    b.HasOne("DogShelter.Services.Database.TipAktivnosti", "TipAktivnosti")
                        .WithMany("AktivnostVolonteras")
                        .HasForeignKey("TipAktivnostiId")
                        .IsRequired()
                        .HasConstraintName("FK_AktivnostVolontera_Tip");

                    b.HasOne("DogShelter.Services.Database.Volonter", "Volonter")
                        .WithMany("AktivnostVolonteras")
                        .HasForeignKey("VolonterId")
                        .IsRequired()
                        .HasConstraintName("FK_AktivnostVolontera_Volonter");

                    b.Navigation("TipAktivnosti");

                    b.Navigation("Volonter");
                });

            modelBuilder.Entity("DogShelter.Services.Database.DogadjajVolonter", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Dogadjaj", "Dogadjaj")
                        .WithMany("DogadjajVolonters")
                        .HasForeignKey("DogadjajId")
                        .IsRequired()
                        .HasConstraintName("FK_DogadjajVolonter_Dogadjaj");

                    b.HasOne("DogShelter.Services.Database.Volonter", "Volonter")
                        .WithMany("DogadjajVolonters")
                        .HasForeignKey("VolonterId")
                        .IsRequired()
                        .HasConstraintName("FK_DogadjajVolonter_Volonter");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Volonter");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Donacija", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("DonacijaKorisniks")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Donacija_Korisnik");

                    b.HasOne("DogShelter.Services.Database.Korisnik", "ObradioKorisnik")
                        .WithMany("DonacijaObradioKorisniks")
                        .HasForeignKey("ObradioKorisnikId")
                        .HasConstraintName("FK_Donacija_ObradioKorisnik");

                    b.HasOne("DogShelter.Services.Database.StatusDonacije", "StatusDonacije")
                        .WithMany("Donacijas")
                        .HasForeignKey("StatusDonacijeId")
                        .IsRequired()
                        .HasConstraintName("FK_Donacija_Status");

                    b.HasOne("DogShelter.Services.Database.TipDonacije", "TipDonacije")
                        .WithMany("Donacijas")
                        .HasForeignKey("TipDonacijeId")
                        .IsRequired()
                        .HasConstraintName("FK_Donacija_Tip");

                    b.Navigation("Korisnik");

                    b.Navigation("ObradioKorisnik");

                    b.Navigation("StatusDonacije");

                    b.Navigation("TipDonacije");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Korisnik", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Grad", "Grad")
                        .WithMany("Korisniks")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK_Korisnik_Grad");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("DogShelter.Services.Database.KorisnikUloga", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikUloga_Korisnik");

                    b.HasOne("DogShelter.Services.Database.Uloga", "Uloga")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("UlogaId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikUloga_Uloga");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("DogShelter.Services.Database.LozinkaResetToken", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("LozinkaResetTokens")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_LozinkaResetToken_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Notifikacija", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("Notifikacijas")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifikacija_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Obavijest", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Autor")
                        .WithMany("Obavijests")
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK_Obavijest_Autor");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Pas", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Rasa", "Rasa")
                        .WithMany("Pas")
                        .HasForeignKey("RasaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pas_Rasa");

                    b.HasOne("DogShelter.Services.Database.StatusPsa", "StatusPsa")
                        .WithMany("Pas")
                        .HasForeignKey("StatusPsaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pas_Status");

                    b.HasOne("DogShelter.Services.Database.VelicinaPsa", "VelicinaPsa")
                        .WithMany("Pas")
                        .HasForeignKey("VelicinaPsaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pas_Velicina");

                    b.Navigation("Rasa");

                    b.Navigation("StatusPsa");

                    b.Navigation("VelicinaPsa");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Posjeta", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("PosjetaKorisniks")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Posjeta_Korisnik");

                    b.HasOne("DogShelter.Services.Database.Korisnik", "ObradioKorisnik")
                        .WithMany("PosjetaObradioKorisniks")
                        .HasForeignKey("ObradioKorisnikId")
                        .HasConstraintName("FK_Posjeta_ObradioKorisnik");

                    b.HasOne("DogShelter.Services.Database.Pas", "Pas")
                        .WithMany("Posjetas")
                        .HasForeignKey("PasId")
                        .HasConstraintName("FK_Posjeta_Pas");

                    b.HasOne("DogShelter.Services.Database.StatusPosjete", "StatusPosjete")
                        .WithMany("Posjeta")
                        .HasForeignKey("StatusPosjeteId")
                        .IsRequired()
                        .HasConstraintName("FK_Posjeta_Status");

                    b.Navigation("Korisnik");

                    b.Navigation("ObradioKorisnik");

                    b.Navigation("Pas");

                    b.Navigation("StatusPosjete");
                });

            modelBuilder.Entity("DogShelter.Services.Database.PregledPsa", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("PregledPsas")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_PregledPsa_Korisnik");

                    b.HasOne("DogShelter.Services.Database.Pas", "Pas")
                        .WithMany("PregledPsas")
                        .HasForeignKey("PasId")
                        .IsRequired()
                        .HasConstraintName("FK_PregledPsa_Pas");

                    b.Navigation("Korisnik");

                    b.Navigation("Pas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.RevokedToken", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("RevokedTokens")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_RevokedToken_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("DogShelter.Services.Database.SlikaPsa", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Pas", "Pas")
                        .WithMany("SlikaPsas")
                        .HasForeignKey("PasId")
                        .IsRequired()
                        .HasConstraintName("FK_SlikaPsa_Pas");

                    b.Navigation("Pas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Udomljavanje", b =>
                {
                    b.HasOne("DogShelter.Services.Database.ZahtjevZaUdomljavanje", "ZahtjevZaUdomljavanje")
                        .WithOne("Udomljavanje")
                        .HasForeignKey("DogShelter.Services.Database.Udomljavanje", "ZahtjevZaUdomljavanjeId")
                        .IsRequired()
                        .HasConstraintName("FK_Udomljavanje_Zahtjev");

                    b.Navigation("ZahtjevZaUdomljavanje");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Volonter", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithOne("Volonter")
                        .HasForeignKey("DogShelter.Services.Database.Volonter", "KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Volonter_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("DogShelter.Services.Database.ZahtjevZaUdomljavanje", b =>
                {
                    b.HasOne("DogShelter.Services.Database.Korisnik", "Korisnik")
                        .WithMany("ZahtjevZaUdomljavanjeKorisniks")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK__ZahtjevZa__Koris__4CA06362");

                    b.HasOne("DogShelter.Services.Database.Korisnik", "ObradioKorisnik")
                        .WithMany("ZahtjevZaUdomljavanjeObradioKorisniks")
                        .HasForeignKey("ObradioKorisnikId")
                        .HasConstraintName("FK__ZahtjevZa__Obrad__4F7CD00D");

                    b.HasOne("DogShelter.Services.Database.Pas", "Pas")
                        .WithMany("ZahtjevZaUdomljavanjes")
                        .HasForeignKey("PasId")
                        .IsRequired()
                        .HasConstraintName("FK__ZahtjevZa__PasId__4D94879B");

                    b.HasOne("DogShelter.Services.Database.StatusZahtjeva", "StatusZahtjeva")
                        .WithMany("ZahtjevZaUdomljavanjes")
                        .HasForeignKey("StatusZahtjevaId")
                        .IsRequired()
                        .HasConstraintName("FK__ZahtjevZa__Statu__4E88ABD4");

                    b.Navigation("Korisnik");

                    b.Navigation("ObradioKorisnik");

                    b.Navigation("Pas");

                    b.Navigation("StatusZahtjeva");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Dogadjaj", b =>
                {
                    b.Navigation("DogadjajVolonters");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Grad", b =>
                {
                    b.Navigation("Korisniks");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Korisnik", b =>
                {
                    b.Navigation("DonacijaKorisniks");

                    b.Navigation("DonacijaObradioKorisniks");

                    b.Navigation("KorisnikUlogas");

                    b.Navigation("LozinkaResetTokens");

                    b.Navigation("Notifikacijas");

                    b.Navigation("Obavijests");

                    b.Navigation("PosjetaKorisniks");

                    b.Navigation("PosjetaObradioKorisniks");

                    b.Navigation("PregledPsas");

                    b.Navigation("RevokedTokens");

                    b.Navigation("Volonter");

                    b.Navigation("ZahtjevZaUdomljavanjeKorisniks");

                    b.Navigation("ZahtjevZaUdomljavanjeObradioKorisniks");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Pas", b =>
                {
                    b.Navigation("Posjetas");

                    b.Navigation("PregledPsas");

                    b.Navigation("SlikaPsas");

                    b.Navigation("ZahtjevZaUdomljavanjes");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Rasa", b =>
                {
                    b.Navigation("Pas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusDonacije", b =>
                {
                    b.Navigation("Donacijas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusPosjete", b =>
                {
                    b.Navigation("Posjeta");
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusPsa", b =>
                {
                    b.Navigation("Pas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.StatusZahtjeva", b =>
                {
                    b.Navigation("ZahtjevZaUdomljavanjes");
                });

            modelBuilder.Entity("DogShelter.Services.Database.TipAktivnosti", b =>
                {
                    b.Navigation("AktivnostVolonteras");
                });

            modelBuilder.Entity("DogShelter.Services.Database.TipDonacije", b =>
                {
                    b.Navigation("Donacijas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Uloga", b =>
                {
                    b.Navigation("KorisnikUlogas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.VelicinaPsa", b =>
                {
                    b.Navigation("Pas");
                });

            modelBuilder.Entity("DogShelter.Services.Database.Volonter", b =>
                {
                    b.Navigation("AktivnostVolonteras");

                    b.Navigation("DogadjajVolonters");
                });

            modelBuilder.Entity("DogShelter.Services.Database.ZahtjevZaUdomljavanje", b =>
                {
                    b.Navigation("Udomljavanje");
                });
#pragma warning restore 612, 618
        }
    }
}
